user: "Amit Oved"

frontend:
  name: todolist-frontend
  replicaCount: 1
  port: 8080
  image:
    repository: ghcr.io/bennyro-mta/todolist-vue
    tag: "1.2"
    pullPolicy: Always
  service:
    type: LoadBalancer
  resources:
    requests:
      memory: "64Mi"
      cpu: "50m"
    limits:
      memory: "128Mi"
      cpu: "100m"
  probes:
    liveness:
      initialDelaySeconds: 15
      periodSeconds: 10
      timeoutSeconds: 2
      failureThreshold: 3
      httpGet:
        path: /
        port: 8080
    readiness:
      initialDelaySeconds: 10
      periodSeconds: 5
      timeoutSeconds: 2
      failureThreshold: 1
      httpGet:
        path: /
        port: 8080
  
  titleImage: "https://raw.githubusercontent.com/Am1its/todolist-k8s/main/myimage.png"

backend:
  name: todos-api
  replicaCount: 1
  image:
    repository: ghcr.io/bennyro-mta/todos-api
    tag: "1.2"
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 8080
  resources: {}
  apiBaseUrl: "http://localhost:8081/todos"

database:
  name: mariadb
  image:
    repository: mariadb
    tag: "10"
    pullPolicy: IfNotPresent
  storageSize: 1Gi
  port: 3306
  rootPassword: "changeme"
  appPassword: "changeme"
  

  networkPolicy:
    enabled: true

ingress:
  enabled: false 
  host: todo.local
