apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
data:
  MYSQL_DB: "todo"
  MYSQL_DATABASE: "todo"
  MYSQL_HOST: "{{ .Values.database.name }}"
  MYSQL_USER: "appuser"
  MYSQL_TABLE: "todos"
  USER: "{{ .Values.user }}"
  API_BASE_URL: "{{ .Values.backend.apiBaseUrl }}"
  VUE_APP_TITLE_IMAGE: "{{ .Values.frontend.titleImage }}"